In [1]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import time

In [2]:
def get_news_reuters(page):
    # url definition
    url = "https://www.reuters.com/news/archive/mcbreakingnews?view=page&page=" + str(page) + "&pageSize=10"

    # Request
    r1 = requests.get(url)
    r1.status_code

    # We'll save in coverpage the cover page content
    coverpage = r1.content

    # Soup
    soup1 = BeautifulSoup(coverpage, "html5lib")

    # News identification
    coverpage_news = soup1.find_all('h3', class_="story-title")
    coverpage_date = soup1.find_all('time')

    # Empty lists for content, links and titles
    list_titles = []
    list_dates = []

    for n in np.arange(0, 10):

        # Getting the title
        title = coverpage_news[n].get_text()
        list_titles.append(title.replace('\t', '').replace('\n',''))

        # Getting the date
        date = coverpage_date[n].find('span').get_text()
        list_dates.append(date)

        # df_show_info
        df_show_info = pd.DataFrame(
        {'Article Title': list_titles,
        'Article Date': list_dates})

    return (df_show_info)

In [3]:
get_news_reuters(100)

                                       Article Title Article Date
0  Factbox: What changes are governments making i...  Jun 11 2020
1  Walmart to stop keeping 'multicultural' beauty...  Jun 11 2020
2  Protesters tear down Christopher Columbus stat...  Jun 11 2020
3  LeBron James backs effort to prevent U.S. blac...  Jun 11 2020
4      NASCAR bans Confederate flag from race tracks  Jun 11 2020
5  Australian PM on China tensions: country won't...  Jun 11 2020
6  China urges Australia to safeguard Chinese cit...  Jun 11 2020
7  Taiwan scrambles to ready for influx from Hong...  Jun 11 2020
8  India lifts export ban on Trump-touted drug hy...  Jun 11 2020
9  Europe sets sights on dud antibody tests amid ...  Jun 11 2020

In [ ]:
list_titles = []
list_dates = []

final_df = pd.DataFrame(
{'Article Title': list_titles,
'Article Date': list_dates})

#append info of each coverpage to final dataframe; theguardian has 1900 pages
for i in range(1,3277):
    final_df = final_df.append(get_news_reuters(i))

In [13]:
final_df

                                       Article Title Article Date
0  Tesla denies reports of firing employees who c...   7:46pm EDT
1  In cloud clash with Alibaba, underdog Tencent ...   7:05pm EDT
2  Facebook hit with complaint alleging widesprea...   6:23pm EDT
3  Factbox: More companies join Facebook ad boyco...   6:05pm EDT
4  Brazil central bank chief says WhatsApp paymen...   5:44pm EDT
5  Facebook, YouTube, Twitter to face same EU rul...   2:00pm EDT
6  Who's to blame for Wirecard? Germany passes th...   1:42pm EDT
7  German watchdog chief calls Wirecard scandal a...   1:42pm EDT
8  EU regulators checking if Fitbit deal will boo...  12:48pm EDT
9  U.S. Senate committee approves anti-child porn...  12:41pm EDT
0  China tech giant Alibaba dismisses livestreami...  12:30pm EDT
1  Tesla to make molecule printers for German COV...  12:26pm EDT
2  SoftBank-backed Lemonade soars 73% in U.S. mar...  12:14pm EDT
3  Faraday Future's Chinese founder completes per...  10:50am EDT
4  EU banks to take on Visa, Mastercard with new ...  10:29am EDT
5  Lithuania dabbles in crypto-coin as central ba...  10:25am EDT
6  Tesla's 'jaw-dropping' second-quarter deliveri...  10:00am EDT
7   Deutsche Bank weighs support for Wirecard's bank   9:43am EDT
8  'Gold mine': European police target secret pho...   9:25am EDT
9  Twitter removes image tweet by Trump over NYT ...   2:52am EDT

In [125]:
final_df.to_csv('cnntech_headlines_dataset.csv')