In [18]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import time

In [19]:
def get_news_reuters(page):
    # url definition
    url = "https://www.reuters.com/news/archive/businessnews?view=page&page=" + str(page) + "&pageSize=10"

    # Request
    r1 = requests.get(url)
    r1.status_code

    # We'll save in coverpage the cover page content
    coverpage = r1.content

    # Soup
    soup1 = BeautifulSoup(coverpage, "html5lib")

    # News identification
    coverpage_news = soup1.find_all('h3', class_="story-title")
    coverpage_date = soup1.find_all('time')

    # Empty lists for content, links and titles
    list_titles = []
    list_dates = []

    for n in np.arange(0, 10):

        # Getting the title
        title = coverpage_news[n].get_text()
        list_titles.append(title.replace('\t', '').replace('\n',''))

        # Getting the date
        date = coverpage_date[n].find('span').get_text()
        list_dates.append(date)

        # df_show_info
        df_show_info = pd.DataFrame(
        {'Article Title': list_titles,
        'Article Date': list_dates})

    return (df_show_info)

In [20]:
get_news_reuters(10)

                                       Article Title Article Date
0  P&G says will not disclose advertising decisio...  Jul 01 2020
1  Manufacturing, vaccine data power stocks highe...  Jul 01 2020
2  Fed mulls promises for the future, appears to ...  Jul 01 2020
3  Citigroup taps RBC banker to co-run software i...  Jul 01 2020
4  Dollar wobbles as decent U.S. data tempers saf...  Jul 01 2020
5  Trump: Getting 'more and more happy' with Fed ...  Jul 01 2020
6  Trump says he will have a statement on the min...  Jul 01 2020
7  Police raid Wirecard HQ as administrator kicks...  Jul 01 2020
8  Oil rises over 1% on U.S. crude stockpile draw...  Jul 01 2020
9  Uber extends mask requirement for drivers, rid...  Jul 01 2020

In [21]:
list_titles = []
list_dates = []

final_df = pd.DataFrame(
{'Article Title': list_titles,
'Article Date': list_dates})

#append info of each coverpage to final dataframe; theguardian has 1900 pages
for i in range(1,3277):
    final_df = final_df.append(get_news_reuters(i))

In [22]:
final_df

                                        Article Title Article Date
0   Delta amends credit facility to include strict...   9:52pm EDT
1   Asian stocks set to follow U.S. jobs rally, Ch...   8:55pm EDT
2   Oil falls as growing coronavirus cases stoke f...   8:52pm EDT
3     Dollar in narrow range as U.S. virus cases grow   8:27pm EDT
4   How Moderna executives are cashing in on COVID...   8:09pm EDT
..                                                ...          ...
5   Ford to temporarily layoff about 2,000 hourly ...  Mar 05 2018
6   Trump trade threats alarm German carmakers, hi...  Mar 05 2018
7   Trump ties steel, aluminum tariffs for Mexico,...  Mar 05 2018
8   As its wealth fund goes green, Norway's firms ...  Mar 05 2018
9   Key U.S. lawmaker urges steel tariff exemption...  Mar 05 2018

[32760 rows x 2 columns]

In [24]:
final_df.to_csv('reutersbusiness_headlines_dataset.csv')