In [1]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import time

In [2]:
def get_news_reuters(page):
    # url definition
    url = "https://www.reuters.com/news/archive/wealthnews?view=page&page=" + str(page) + "&pageSize=10"

    # Request
    r1 = requests.get(url)
    r1.status_code

    # We'll save in coverpage the cover page content
    coverpage = r1.content

    # Soup
    soup1 = BeautifulSoup(coverpage, "html5lib")

    # News identification
    coverpage_news = soup1.find_all('h3', class_="story-title")
    coverpage_date = soup1.find_all('time')

    # Empty lists for content, links and titles
    list_titles = []
    list_dates = []

    for n in np.arange(0, 10):

        # Getting the title
        title = coverpage_news[n].get_text()
        list_titles.append(title.replace('\t', '').replace('\n',''))

        # Getting the date
        date = coverpage_date[n].find('span').get_text()
        list_dates.append(date)

        # df_show_info
        df_show_info = pd.DataFrame(
        {'Article Title': list_titles,
        'Article Date': list_dates})

    return (df_show_info)

In [3]:
get_news_reuters(100)

                                       Article Title Article Date
0  Factbox: What changes are governments making i...  Jun 11 2020
1  Walmart to stop keeping 'multicultural' beauty...  Jun 11 2020
2  Protesters tear down Christopher Columbus stat...  Jun 11 2020
3  LeBron James backs effort to prevent U.S. blac...  Jun 11 2020
4      NASCAR bans Confederate flag from race tracks  Jun 11 2020
5  Australian PM on China tensions: country won't...  Jun 11 2020
6  China urges Australia to safeguard Chinese cit...  Jun 11 2020
7  Taiwan scrambles to ready for influx from Hong...  Jun 11 2020
8  India lifts export ban on Trump-touted drug hy...  Jun 11 2020
9  Europe sets sights on dud antibody tests amid ...  Jun 11 2020

In [4]:
list_titles = []
list_dates = []

final_df = pd.DataFrame(
{'Article Title': list_titles,
'Article Date': list_dates})

#append info of each coverpage to final dataframe; theguardian has 1900 pages
for i in range(1,3277):
    final_df = final_df.append(get_news_reuters(i))

In [6]:
final_df

                                        Article Title Article Date
0   U.S. coronavirus cases hit new global record, ...   9:25pm EDT
1   Asian stocks set to follow U.S. jobs rally, Ch...   8:55pm EDT
2   U.S. sees 51,000 new COVID-19 cases, infection...   8:33pm EDT
3   Jeffrey Epstein friend Ghislaine Maxwell arres...   8:15pm EDT
4   'A good place to hide:' New Hampshire locals h...   8:15pm EDT
..                                                ...          ...
5   Australia to consider taking in Saudi teen who...  Jan 09 2019
6   In Oval Office speech, Trump demands a wall bu...  Jan 09 2019
7   Trump administration says it will provide food...  Jan 09 2019
8   Exclusive: Fiat Chrysler nearing U.S. diesel e...  Jan 09 2019
9   Harvey Weinstein's sexual assault trial set fo...  Jan 09 2019

[32760 rows x 2 columns]

In [5]:
final_df.to_csv('reuterswealth_headlines_dataset.csv')